name: DynmapWebAPI
version: '${project.version}'
main: de.kesuaheli.dynmapwebapi.DynmapWebAPI
api-version: '1.20'
authors: [Kesuaheli]
description: DynmapWebAPI exposes some http endpoints to change some dynmap settings
website: https://kesuaheli.de

depend:
  - dynmap

commands:
  dynmapwebapi:
    description: Admin controls for the DynmapWebAPI
    permission: de.kesuaheli.dynmapwebapi.command.admin
    usage: /<command> <reload|restart> [params]
    aliases:
      - dynmapapi
      - dmapapi

permissions:
  de.kesuaheli.dynmapwebapi.command.admin:
    description: Allows usage of the /dynmapwebapi command to do admin stuff
    default: op
